// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT1--QOCxriKON0uAuSd-PETQi4cUBYq4',
    appId: '1:802565511046:web:6bea316294425640f57e07',
    messagingSenderId: '802565511046',
    projectId: 'ripot-4edf7',
    authDomain: 'ripot-4edf7.firebaseapp.com',
    storageBucket: 'ripot-4edf7.firebasestorage.app',
    measurementId: 'G-YKDGNTD8FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFop_HXjyU3NSywNBePYofediCeTyj2HU',
    appId: '1:802565511046:android:9a0015539a64e9aff57e07',
    messagingSenderId: '802565511046',
    projectId: 'ripot-4edf7',
    storageBucket: 'ripot-4edf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1YyKHhACjnoBqslTvadvMEWUx3wctdoI',
    appId: '1:802565511046:ios:8d1bb54fe3ce6bcef57e07',
    messagingSenderId: '802565511046',
    projectId: 'ripot-4edf7',
    storageBucket: 'ripot-4edf7.firebasestorage.app',
    iosBundleId: 'com.example.report',
  );
}
